"""Tests for PRISM Step 15: Policy Comparison Engine & Cross-Policy Retrieval."""

import pytest
from unittest.mock import MagicMock, patch
from fastapi.testclient import TestClient
from app.main import app
from app.api.deps import get_current_user, AuthenticatedUser


client = TestClient(app)


def test_policy_comparison_retrieval_flow():
    """Verify evidence retrieval works for comparing two policies under the user's session."""
    user = AuthenticatedUser(
        user_data={"id": "usr_compare_1", "email": "compare@prism.in", "role": "authenticated"},
        token="token_compare_1",
    )

    app.dependency_overrides[get_current_user] = lambda: user
    try:
        with patch("app.api.routes.retrieval.RetrievalService") as mock_retrieval_cls:
            mock_service = MagicMock()
            mock_retrieval_cls.return_value = mock_service
            mock_service.retrieve_relevant_chunks.return_value = [
                {
                    "chunk_id": "chk_ped_1",
                    "document_id": "doc_pol_a",
                    "policy_id": "pol_care_a",
                    "page_number": 8,
                    "section_title": "Waiting Periods",
                    "content": "Pre-existing diseases covered after 36 months of continuous coverage.",
                    "similarity": 0.88,
                }
            ]

            resp = client.post(
                "/api/retrieval/search",
                json={
                    "query": "pre-existing disease waiting period PED months exclusions",
                    "policy_id": "pol_care_a",
                    "top_k": 3,
                },
            )

            assert resp.status_code == 200
            data = resp.json()
            assert "results" in data
            assert len(data["results"]) == 1
            assert data["results"][0]["page_number"] == 8
            assert data["results"][0]["section_title"] == "Waiting Periods"
            assert "36 months" in data["results"][0]["content"]

            mock_retrieval_cls.assert_called_once_with(user_token="token_compare_1")
    finally:
        app.dependency_overrides.pop(get_current_user, None)


def test_policy_comparison_cross_user_isolation():
    """Verify that a user cannot query evidence for another user's policy during comparison."""
    user = AuthenticatedUser(
        user_data={"id": "usr_compare_2", "email": "compare2@prism.in", "role": "authenticated"},
        token="token_compare_2",
    )

    app.dependency_overrides[get_current_user] = lambda: user
    try:
        with patch("app.api.routes.retrieval.RetrievalService") as mock_retrieval_cls:
            mock_service = MagicMock()
            mock_retrieval_cls.return_value = mock_service
            # Service enforces policy ownership; returns empty list if user is unauthorized
            mock_service.retrieve_relevant_chunks.return_value = []

            resp = client.post(
                "/api/retrieval/search",
                json={
                    "query": "room rent capping limit",
                    "policy_id": "pol_unauthorized_99",
                    "top_k": 5,
                },
            )

            assert resp.status_code == 200
            data = resp.json()
            assert data["results"] == []
    finally:
        app.dependency_overrides.pop(get_current_user, None)


def test_comparison_neutrality_and_missing_data_rules():
    """Verify neutrality invariants: no recommendation bias, no fabricated defaults."""
    forbidden_terms = [
        "winner",
        "better policy",
        "best policy",
        "recommended policy",
        "buy policy a",
        "buy policy b",
        "policy b is superior",
        "superior policy",
    ]

    # Sample comparison text generated by PRISM comparison logic
    sample_key_differences = [
        "Care Supreme states a higher stated sum insured (₹15,00,000) than Optima Restore (₹10,00,000).",
        "Optima Restore states a 36-month waiting period for pre-existing diseases, whereas Care Supreme specifies 24 months.",
        "Care Supreme states no room rent capping, while Optima Restore states 1% of Sum Insured.",
    ]

    for statement in sample_key_differences:
        lower_statement = statement.lower()
        for forbidden in forbidden_terms:
            assert forbidden not in lower_statement, f"Found non-neutral word '{forbidden}' in '{statement}'"

    missing_text = "Not clearly stated in the available policy evidence."
    # Missing information should not default to "unlimited" or "no waiting period"
    assert missing_text != "Unlimited"
    assert missing_text != "No waiting period"
    assert missing_text != "Not applicable"
